title: Nathan Chen
logo: /assets%20img/20251225_153516.jpg
description: >
  Aspiring Data Scientist with internship experience across SaaS, AI, and FoodTech. Recent Data Science graduate from UC Berkeley. Passionate about AI. US Citizen
  <br><br>
  <a href="https://www.linkedin.com/in/nathanchen291/" style="font-weight: bold; color: #0076A8;">View my LinkedIn Profile</a>
show_downloads: false
theme: jekyll-theme-minimal
