title: Nathan Chen
logo: /assets%20img/20251225_153516.jpg
description: >
  Aspiring Data Scientist with internship experience across SaaS, AI, and FoodTech.
  <br><br>
  Recent Data Science graduate from UC Berkeley.
  <br><br>
  Passionate about AI â€¢ US Citizen
show_donwloads: false
theme: jekyll-theme-minimal
